export class OpdOutPatient {
    id:number;
    opd_details_id:number;
    organisation_id:number;
    patient_charge_id:number;
    transaction_id:number;
    cons_doctor:number;
    case_type:string;
    appointment_date:Date;
    symptoms_type:number;
    symptoms:string;
    bp:string;
    height:string;
    weight:string;
    pulse:string;
    temperature:string;
    respiration:string;
    known_allergies:string;
    patient_old:string;
    casualty:string;
    refference:string;
    date:string;
    note:string;
    note_remark:string;
    payment_mode:string;
    generated_by:string;
    live_consult:string;
    can_delete:string;
    payment_date:Date;
    time:string;
    created_at:Date;
    patient_id:number;
    Hospital_id:number;

}
